name: Run RuboCop

on: 
  push:
    branches:
      - '**'

jobs:
  vm-job:
    name: RuboCop check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop -P
