name: RuboCop

on:
  push:
    paths:
      - /**

jobs:
  vm-job:
    name: RuboCop check
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: ./
          ruby-version: '3.2.2'
          bundler-cache: true
      - name: Run RuboCop
        working-directory: ./
        run: bundle exec rubocop -P
